### ISSUE TITLE
when i try to use ankimote on linux it gives me this error 

### ISSUE THREAD

**Issue by Mahgozar** [TheDabblingDuck/ankimote#36]
Caught exception:
Traceback (most recent call last):
  File "urllib3/connection.py", line 169, in _new_conn
  File "urllib3/util/connection.py", line 73, in create_connection
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 699, in urlopen
  File "urllib3/connectionpool.py", line 394, in _make_request
  File "urllib3/connection.py", line 234, in request
  File "http/client.py", line 1230, in request
  File "http/client.py", line 1276, in _send_request
  File "http/client.py", line 1225, in endheaders
  File "http/client.py", line 1004, in _send_output
  File "http/client.py", line 944, in send
  File "urllib3/connection.py", line 200, in connect
  File "urllib3/connection.py", line 181, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0c7c0d2a00>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 439, in send
  File "urllib3/connectionpool.py", line 755, in urlopen
  File "urllib3/util/retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.google-analytics.com', port=80): Max retries exceeded with url: /collect (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0c7c0d2a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt/webview.py", line 41, in cmd
  File "aqt/webview.py", line 142, in _onCmd
  File "aqt/webview.py", line 595, in _onBridgeCmd
  File "aqt/toolbar.py", line 168, in _linkHandler
  File "/home/zmey/.local/share/Anki2/addons21/149004221/__init__.py", line 346, in runRemote
    requests.post("http://www.google-analytics.com/collect", data=payloadSession)
  File "requests/api.py", line 119, in post
  File "requests/api.py", line 61, in request
  File "requests/sessions.py", line 542, in request
  File "requests/sessions.py", line 655, in send
  File "requests/adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.google-analytics.com', port=80): Max retries exceeded with url: /collect (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0c7c0d2a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by TheDabblingDuck** [comment]
Seems like it's not able to connect to google analytics. Do you have a system or network wide adblocker? 

In any case, you can fix this issue by finding the addon file. Go to tools > addons > ankimote > open folder (which should open up `/home/zmey/.local/share/Anki2/addons21/149004221/`) and open the `__init__.py` file. 

Find the 2 lines starting with `requests.post` and delete them, then restart Anki and try again.

**Comment by Mahgozar** [comment]
thank you!
