### ISSUE TITLE
When i use ankimote this happens.

### ISSUE THREAD

**Issue by JejTr** [TheDabblingDuck/ankimote#39]
Hi i love this addon a lot, but in my linux computer, when i connect and start to use, some accions doesn't work and anki display this message:(
> Error
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
> If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
> When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
> Debug info:
> Anki 2.1.52 (ab1c2395) Python 3.9.10 Qt 6.3.0 PyQt 6.3.0
> Platform: Linux
> Flags: frz=True ao=True sv=3
> Add-ons, last update check: 2022-06-22 19:25:51
> 
> Caught exception:Error
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
> If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
> When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
> Debug info:
> Anki 2.1.52 (ab1c2395) Python 3.9.10 Qt 6.3.0 PyQt 6.3.0
> Platform: Linux
> Flags: frz=True ao=True sv=3
> Add-ons, last update check: 2022-06-22 19:25:51
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt.taskman", line 122, in _on_closures_pending
>   File "aqt.taskman", line 71, in <lambda>
>   File "aqt.taskman", line 90, in wrapped_done
>   File "aqt.operations", line 125, in wrapped_done
>   File "aqt.reviewer", line 434, in after_answer
>   File "aqt.reviewer", line 450, in _after_answering
>   File "aqt.reviewer", line 898, in check_timebox
>   File "anki.collection", line 1184, in timeboxReached
>   File "anki._legacy", line 78, in __getattr__
> AttributeError: 'Collection' object has no attribute '_startTime'
> 
> Traceback (most recent call last):
>   File "aqt.taskman", line 122, in _on_closures_pending
>   File "aqt.taskman", line 71, in <lambda>
>   File "aqt.taskman", line 90, in wrapped_done
>   File "aqt.operations", line 125, in wrapped_done
>   File "aqt.reviewer", line 434, in after_answer
>   File "aqt.reviewer", line 450, in _after_answering
>   File "aqt.reviewer", line 898, in check_timebox
>   File "anki.collection", line 1184, in timeboxReached
>   File "anki._legacy", line 78, in __getattr__
> AttributeError: 'Collection' object has no attribute '_startTime'

**Comment by TheDabblingDuck** [comment]
Hi are you sure this error is related to this addon? Does it continue to happen if you disable all other addons and have only Ankimote enabled? It may be a conflict with another addon, or an unrelated issue, since I'm not seeing anything in that error message related to Ankimote.
