### ISSUE TITLE
Can't grade the cards using ankimote on 2.1.54

### ISSUE THREAD

**Issue by LennartPhil** [TheDabblingDuck/ankimote#44]
Unfortunately I get an error message, whenever I try to swipe the cards, although displaying the answer does work.

Error message:

> Error
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
> If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
> When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
> Debug info:
> Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
> Platform: Mac 12.5.1
> Flags: frz=True ao=True sv=3
> Add-ons, last update check: 2023-01-26 09:50:48
> Add-ons possibly involved: ⁨Ankimote - remote to control Anki from your phone⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "urllib3.connection", line 174, in _new_conn
>   File "urllib3.util.connection", line 95, in create_connection
>   File "urllib3.util.connection", line 85, in create_connection
> ConnectionRefusedError: [Errno 61] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "urllib3.connectionpool", line 703, in urlopen
>   File "urllib3.connectionpool", line 398, in _make_request
>   File "urllib3.connection", line 239, in request
>   File "http.client", line 1279, in request
>   File "http.client", line 1325, in _send_request
>   File "http.client", line 1274, in endheaders
>   File "http.client", line 1034, in _send_output
>   File "http.client", line 974, in send
>   File "urllib3.connection", line 205, in connect
>   File "urllib3.connection", line 186, in _new_conn
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x13cdf5460>: Failed to establish a new connection: [Errno 61] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "requests.adapters", line 440, in send
>   File "urllib3.connectionpool", line 785, in urlopen
>   File "urllib3.util.retry", line 592, in increment
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.google-analytics.com', port=80): Max retries exceeded with url: /collect (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x13cdf5460>: Failed to establish a new connection: [Errno 61] Connection refused'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/LennartPhilipp/Library/Application Support/Anki2/addons21/149004221/__init__.py", line 266, in handleMessage
>     requests.post("http://www.google-analytics.com/collect", data=payloadAnsCard)
>   File "requests.api", line 117, in post
>   File "requests.api", line 61, in request
>   File "requests.sessions", line 529, in request
>   File "requests.sessions", line 645, in send
>   File "requests.adapters", line 519, in send
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.google-analytics.com', port=80): Max retries exceeded with url: /collect (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x13cdf5460>: Failed to establish a new connection: [Errno 61] Connection refused'))

**Comment by TheDabblingDuck** [comment]
Seems like the same issue as this one:

https://github.com/TheDabblingDuck/ankimote/issues/36
