### ISSUE TITLE
Ankimote not working

### ISSUE THREAD

**Issue by sjacob255** [TheDabblingDuck/ankimote#52]
I am not sure if this is a me issue but I installed the Ankimote add on and for some reason the page does not load up on my phone when I scan the QR code. I have even tried deleting and reinstalling it. It worked the first day but never worked after that. Both my computer and my iPhone are on the same wifi too

**Comment by forestanki** [comment]
I have the same problem. I think it started, when I downloaded the new anki version but I'm not sure 
I would be really happy, if somebody could help fixing the issue

**Comment by TheDabblingDuck** [comment]
I can't seem to recreate this behavior when testing with the latest stable Anki on Linux.

Could you share any more info? Especially operating system , operating system version, and any firewall configuration you have looked at. Additionally, if you know how to run anki from the command line, the addon does write log messages in the command line output that might be helpful. 

The most common reasons Ankimote doesn't connect on the same home wifi network is firewall on the computer and VPN on computer or phone.

**Comment by forestanki** [comment]
I haven a MacBook Pro wirh MacOS version 15.6.1 (24G90). May anki version is 25.07.5. I don't have any firewall configuration except the one, that was on my Mac since the beginning. Sadly I also don't know how to "run Anki from the command line".

When trying to connect my mobile with ankimote, it shows this text:
_"An error has occurred. For steps to resolve the error if necessary, see help
Possible causal extensions: ankimote - remote to control anki from your phone"_
and I have the option to press a button names "copy debug information"

The copied information is the following:

```
Exception occurred during processing of request from ('192.168.178.22', 63499)
Traceback (most recent call last):
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myname/Library/Application Support/Anki2/addons21/149004221/__init__.py", line 103, in __init__
    super().__init__(*args, directory=DIRECTORY, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/http/server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    ~~~~~~~~~~~^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/http/server.py", line 404, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/socket.py", line 719, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
OSError: [Errno 57] Socket is not connected
```

**Comment by TheDabblingDuck** [comment]
Can you confirm that "iCloud Private Relay" on your computer is off?
https://support.apple.com/guide/mac-help/use-icloud-private-relay-mchlecadabe0/mac

And try adding anki to the firewall and set it to allow incoming
connections ?
https://support.apple.com/guide/mac-help/change-firewall-settings-on-mac-mh11783/mac

**Comment by forestanki** [comment]
Yes, "iCloud Private Relay" was and is turned off, and anki was already added to the firewall as well as it was set to allow incoming connections

**Comment by TheDabblingDuck** [comment]
Unfortunately I can't figure out much more from.thr error message, I'd
encourage you to try with a different computer on the same network to see
if the problem is specific to your computer.

**Comment by forestanki** [comment]
Maybe you could help me running Anki from the command line? I don't know what that is and google isn't helpful either
I can open anki withe the MacOS App "Terminal"

If I try to use the button for ankimote and scanning the QR-code it shows the following code (it's a bit more than the code above but mostly the same):

```
Initializing new WSS
Initializing new http Server
AnkiSocketServer run on port: 61338
----------------------------------------
Exception occurred during processing of request from ('192.168.178.22', 51604)
Traceback (most recent call last):
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myname/Library/Application Support/Anki2/addons21/149004221/__init__.py", line 103, in __init__
    super().__init__(*args, directory=DIRECTORY, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/http/server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    ~~~~~~~~~~~^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/http/server.py", line 404, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/socket.py", line 719, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
OSError: [Errno 57] Socket is not connected
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('192.168.178.22', 51606)
Traceback (most recent call last):
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myname/Library/Application Support/Anki2/addons21/149004221/__init__.py", line 103, in __init__
    super().__init__(*args, directory=DIRECTORY, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/http/server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    ~~~~~~~~~~~^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/http/server.py", line 404, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/myname/Library/Application Support/AnkiProgramFiles/python/cpython-3.13.5-macos-x86_64-none/lib/python3.13/socket.py", line 719, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
OSError: [Errno 57] Socket is not connected
----------------------------------------
Qt warning: QObject::disconnect: wildcard call disconnects from destroyed signal of QPushButton::unnamed 
Qt warning: QObject::disconnect: wildcard call disconnects from destroyed signal of QPushButton::unnamed 
```

Does this help more?

**Comment by forestanki** [comment]
Hi, I just downloaded Anki 25.02 again and with this version Ankimote works just fine. But with Anki 25.07.5 I had the said problems on my Mac
